# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Gui1(object):
    def setupUi(self, Gui1):
        Gui1.setObjectName("Gui1")
        Gui1.resize(322, 283)
        self.Title_label = QtWidgets.QLabel(parent=Gui1)
        self.Title_label.setGeometry(QtCore.QRect(40, 10, 241, 51))
        self.Title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title_label.setObjectName("Title_label")
        self.push_submit = QtWidgets.QPushButton(parent=Gui1)
        self.push_submit.setGeometry(QtCore.QRect(100, 150, 100, 32))
        self.push_submit.setObjectName("push_submit")
        self.Number_Student = QtWidgets.QLineEdit(parent=Gui1)
        self.Number_Student.setGeometry(QtCore.QRect(40, 100, 251, 41))
        self.Number_Student.setObjectName("Number_Student")
        self.label_editLine = QtWidgets.QLabel(parent=Gui1)
        self.label_editLine.setGeometry(QtCore.QRect(40, 70, 241, 16))
        self.label_editLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_editLine.setObjectName("label_editLine")

        self.retranslateUi(Gui1)
        QtCore.QMetaObject.connectSlotsByName(Gui1)

    def retranslateUi(self, Gui1):
        _translate = QtCore.QCoreApplication.translate
        Gui1.setWindowTitle(_translate("Gui1", "GUI"))
        self.Title_label.setText(_translate("Gui1", "GRADING CALCULATOR"))
        self.push_submit.setText(_translate("Gui1", "submit"))
        self.label_editLine.setText(_translate("Gui1", "Enter The Number Of Students"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gui1 = QtWidgets.QWidget()
    ui = Ui_Gui1()
    ui.setupUi(Gui1)
    Gui1.show()
    sys.exit(app.exec())
