# Form implementation generated from reading ui file 'GUI2.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Gui2(object):
    def setupUi(self, Gui2):
        Gui2.setObjectName("Gui2")
        Gui2.resize(400, 533)
        self.TitleLabel = QtWidgets.QLabel(parent=Gui2)
        self.TitleLabel.setGeometry(QtCore.QRect(80, 10, 241, 51))
        self.TitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gradeBox = QtWidgets.QLineEdit(parent=Gui2)
        self.gradeBox.setGeometry(QtCore.QRect(40, 140, 341, 21))
        self.gradeBox.setText("")
        self.gradeBox.setObjectName("gradeBox")
        self.EnterLabel = QtWidgets.QLabel(parent=Gui2)
        self.EnterLabel.setGeometry(QtCore.QRect(40, 110, 131, 21))
        self.EnterLabel.setObjectName("EnterLabel")
        self.BigLabel = QtWidgets.QLabel(parent=Gui2)
        self.BigLabel.setGeometry(QtCore.QRect(40, 170, 310, 240))
        self.BigLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BigLabel.setObjectName("BigLabel")
        self.ClearPush = QtWidgets.QPushButton(parent=Gui2)
        self.ClearPush.setGeometry(QtCore.QRect(20, 470, 100, 32))
        self.ClearPush.setObjectName("ClearPush")
        self.ConvertPush = QtWidgets.QPushButton(parent=Gui2)
        self.ConvertPush.setGeometry(QtCore.QRect(260, 470, 121, 31))
        self.ConvertPush.setObjectName("ConvertPush")
        self.LabelForStudent = QtWidgets.QLabel(parent=Gui2)
        self.LabelForStudent.setGeometry(QtCore.QRect(40, 60, 171, 16))
        self.LabelForStudent.setObjectName("LabelForStudent")
        self.studentsLabelNum = QtWidgets.QLabel(parent=Gui2)
        self.studentsLabelNum.setGeometry(QtCore.QRect(240, 60, 58, 16))
        self.studentsLabelNum.setObjectName("studentsLabelNum")
        self.SubPush = QtWidgets.QPushButton(parent=Gui2)
        self.SubPush.setGeometry(QtCore.QRect(130, 470, 100, 32))
        self.SubPush.setObjectName("SubPush")
        self.AvgLabel = QtWidgets.QLabel(parent=Gui2)
        self.AvgLabel.setGeometry(QtCore.QRect(40, 440, 310, 20))
        self.AvgLabel.setText("")
        self.AvgLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AvgLabel.setObjectName("AvgLabel")
        self.EditPush = QtWidgets.QPushButton(parent=Gui2)
        self.EditPush.setGeometry(QtCore.QRect(220, 80, 100, 32))
        self.EditPush.setObjectName("EditPush")

        self.retranslateUi(Gui2)
        QtCore.QMetaObject.connectSlotsByName(Gui2)

    def retranslateUi(self, Gui2):
        _translate = QtCore.QCoreApplication.translate
        Gui2.setWindowTitle(_translate("Gui2", "Form"))
        self.TitleLabel.setText(_translate("Gui2", "GRADING CALCULATOR"))
        self.EnterLabel.setText(_translate("Gui2", "Enter Grades:"))
        self.BigLabel.setText(_translate("Gui2", "Example to Type 30 40 50 60\nONLY Integers no commas"))
        self.ClearPush.setText(_translate("Gui2", "Clear"))
        self.ConvertPush.setText(_translate("Gui2", "Convert to CSV"))
        self.LabelForStudent.setText(_translate("Gui2", "Number of Students"))
        self.studentsLabelNum.setText(_translate("Gui2", "TextLabel"))
        self.SubPush.setText(_translate("Gui2", "Submit"))
        self.EditPush.setText(_translate("Gui2", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gui2 = QtWidgets.QWidget()
    ui = Ui_Gui2()
    ui.setupUi(Gui2)
    Gui2.show()
    sys.exit(app.exec())
